### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by CybermindDBS** [YouCount/youcount.github.io#6]
When I search a YouTuber it just says "Loading" and none of the suggestions appear...

**Comment by 20manas** [comment]
I just checked. Everything appears to be working. It may have been caused because of a weak internet connection. Try to check again whether it is working or not. If it's not, then revert back here, but please add more details surrounding the issue such as:

1. The page on which the issue is occurring
2. The search query you are entering
3. Other relevant information
