### ISSUE TITLE
Youtube DATA API V3 - Quota 

### ISSUE THREAD

**Issue by mariopattan** [YouCount/youcount.github.io#8]
Hi, I tried your code with my own Youtube Data API v3 key and it worked.

But, after 1 hour running the pew die pie vs t-series live count page, the live count stop working. And it turn's out that the Youtube Data API v3 request "youtube.channels.list" hikes up and reach the 10,000 queries daily limit. Is it normal? 

How to solve it? I saw that socialblade and other platform also using youtube live count too. Thanks

**Comment by AryaDeepanshu** [comment]
It is normal, Actually, when you use API(s) they have request limits
depending on the owner, Google API(s) have some limits but they are enough
for some startup/Intermediate. You may search about Google API(s) and know
more about them

**Comment by 20manas** [comment]
As @AryaDeepanshu said, it's completely normal as there are allocated quotas for different APIs. You can ask Google for an increase in quotas or reduce your usage. I don't know how you're using the API requests, but try to use the requests less often or reduce per request usage by using filters and specific fields options.

Also, since you are making this subscriber counter right now, I must inform you that all the subscriber counters, including the most famous ones like SocialBlade's, will stop working in the upcoming months due to changes made by YouTube in its API policies.
